### ISSUE TITLE
I can't run run.py -- getting errors

### ISSUE THREAD

**Issue by MikeyBeez** [facebookresearch/rebel#9]
Thank you for sharing this code.  I'm looking forward to testing it.  

I made a conda env with python 3.7.  I'm on Pop!_OS 20.04 which is essentially Ubuntu 20.04.  I'm able to make the file, but when I run it thus:  

```
run.py --adhoc --cfg conf/c02_selfplay/liars_sp.yaml \
env.num_dice=1 \
env.num_faces=4 \
env.subgame_params.use_cfr=true \
selfplay.cpu_gen_threads=60
```

I get these messages:Traceback (most recent call last):
  File "run.py", line 25, in <module>
    import cfvpy.tasks
  File "/home/bard/Code/rebel/cfvpy/tasks.py", line 15, in <module>
    import cfvpy.selfplay
  File "/home/bard/Code/rebel/cfvpy/selfplay.py", line 27, in <module>
    import cfvpy.rela
ImportError: /home/bard/Code/rebel/cfvpy/rela.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass

**Comment by yffbit** [comment]
Do you activate the correct conda env before you run it?

**Comment by MikeyBeez** [comment]
Yes.  Here's my terminal including my prompt:  python3 ./run.py
Traceback (most recent call last):
  File "./run.py", line 25, in <module>
    import cfvpy.tasks
  File "/home/bard/Code/rebel/cfvpy/tasks.py", line 15, in <module>
    import cfvpy.selfplay
  File "/home/bard/Code/rebel/cfvpy/selfplay.py", line 27, in <module>
    import cfvpy.rela
ImportError: /home/bard/Code/rebel/cfvpy/rela.cpython-37m-x86_64-linux-gnu.so: undefined symbol: THPVariableClass
╭─░▒▓  ──────────────────────────────────────────────────────────────────────── 1 ✘ ▓▒░─╮
├─░▒▓ on   master !2 ?1                                 rebel   at 11:35:06 AM  ▓▒░─┤
├─░▒▓  ~/Code/rebel                                                                     ─┤

╰─❯ 

Here are my packages:
conda list
# packages in environment at /home/bard/miniconda3/envs/rebel:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
absl-py                   0.11.0                   pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
black                     19.10b0                  pypi_0    pypi
blas                      1.0                         mkl  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2020.10.14                    0  
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.12.5        py37h06a4308_0  
chardet                   3.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
cmake                     3.18.2               ha30ef3c_0  
cudatoolkit               11.0.221             h6bb024c_0  
decorator                 4.4.2                    pypi_0    pypi
expat                     2.2.10               he6710b0_2  
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
google-auth               1.23.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
grpcio                    1.34.0                   pypi_0    pypi
hydra-core                0.1.5                     dev_0    <develop>
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        3.1.1                    pypi_0    pypi
intel-openmp              2020.2                      254  
ipython                   7.19.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
krb5                      1.18.2               h173b8e3_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuv                     1.40.0               h7b6447c_0  
lz4-c                     1.9.2                heb0550a_3  
markdown                  3.3.3                    pypi_0    pypi
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.2.0            py37h23d657b_0  
mkl_random                1.1.1            py37h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.2           py37hff7bd54_0  
nose                      1.3.7                    pypi_0    pypi
numpy                     1.16.4                   pypi_0    pypi
numpy-base                1.19.2           py37hfa32c7d_0  
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                     py37_0  
omegaconf                 1.4.1                    pypi_0    pypi
openssl                   1.1.1h               h7b6447c_0  
pandas                    1.1.5                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pathspec                  0.8.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    8.0.1            py37he98fc37_0  
pip                       20.3.1           py37h06a4308_0  
prompt-toolkit            3.0.8                    pypi_0    pypi
protobuf                  3.14.0                   pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.7.3                    pypi_0    pypi
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                    pypi_0    pypi
pytorch                   1.7.0           py3.7_cuda11.0.221_cudnn8.0.3_0    pytorch
pytorch-lightning         0.5.3.2                   dev_0    <develop>
pytz                      2020.4                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
regex                     2020.11.13               pypi_0    pypi
requests                  2.25.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rhash                     1.4.0                h1ba5d50_0  
rsa                       4.6                      pypi_0    pypi
scikit-learn              0.20.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
setuptools                51.0.0           py37h06a4308_2  
six                       1.15.0           py37h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
submitit                  1.1.5                    pypi_0    pypi
tensorboard               2.4.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
test-tube                 0.7.5                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
toml                      0.10.2                   pypi_0    pypi
torch                     1.4.0                    pypi_0    pypi
torchaudio                0.7.0                      py37    pytorch
torchvision               0.5.0                    pypi_0    pypi
tqdm                      4.35.0                   pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typed-ast                 1.4.1                    pypi_0    pypi
typing_extensions         3.7.4.3                    py_0  
urllib3                   1.26.2                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.1             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0

**Comment by MikeyBeez** [comment]
Python 3.7.9

**Comment by akhti** [comment]
You running pytorch 1.7.0 that has different C++ API than 1.4.0 that the code was built for.
Try switching to 1.40 and doing `make clean all`

**Comment by ghimiremukesh** [comment]
Has anyone run into the following error?

model_locker = cfvpy.rela.ModelLocker(ref_model, act_device)
RuntimeError: Unable to cast Python instance of type <class 'torch._C.ScriptModule'> to C++ type 'torch::jit::script::Module'

**Comment by WZX1998** [comment]
> You running pytorch 1.7.0 that has different C++ API than 1.4.0 that the code was built for.
> Try switching to 1.40 and doing `make clean all`

Hello, I ran into the same problem. I use the pytorch 1.4.0 version. However I still can't find the rela...
Btw I use python 3.7.11
